--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Lycol50/cucumber
build-by-default: true
branches:
- master
projects:
  cucumber:
    path: ""
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.1
        branch: master
      - src: adeynes/asyncio/asyncio
        version: ^0.2.0
        branch: master
      - src: poggit/libasynql/libasynql
        version: ^3.3.2
        branch: master
      - src : adeynes/parsecmd/parsecmd
        version: ^5.0.1
        branch: master
...
